### ISSUE TITLE
crash on load up 1.14.4 (fabric)

### ISSUE THREAD

**Issue by SDUBZ** [AlexiyOrlov/fabric-energy-api#1]
[crash-2019-08-04_20.37.31-client.txt](https://github.com/AlexiyOrlov/fabric-energy-api/files/3464812/crash-2019-08-04_20.37.31-client.txt)
crash report

**Comment by AlexiyOrlov** [comment]
Download Protos 1.14.4-1.0.2 (you have 1.0.1).
Also wrong place for crash report, it is not caused by Energies.
